### ISSUE TITLE
Chapter 2 Notes, Errata, and Discussion: Setting Up

### ISSUE THREAD

**Issue by lihaoyi** [handsonscala/handsonscala#2]
Thread to discuss anything and everything about Chapter 2. Important topics will be folded into the issue description.

**Comment by yelinaung** [comment]
I am not sure if this is the correct way to open the discussion but I just wanna report something about the installation.

#### Installation Error on Linux 

I've followed [the guide on chapter 2](https://www.handsonscala.com/chapter-2-setting-up.html#2-3-installing-ammonite) about the installation on Mac/Linux. I am on Ubuntu 18.04.4 LTS with zsh.

```bash
λ ~/ sudo curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.0.4/2.13-2.0.4 > /usr/local/bin/amm
zsh: permission denied: /usr/local/bin/amm
```

I belive it does not work because the redirection is performed by the shell which does not have the permission to write to `/usr/local/bin/amm`. Am I missing something here?

I've tried a few alternative ways and they seem to be working.
```bash
# with redirection
sudo sh -c 'sudo curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.0.4/2.13-2.0.4 > /usr/local/bin/amm'

# without redirection
sudo curl -L 'https://github.com/lihaoyi/Ammonite/releases/download/2.0.4/2.13-2.0.4' -o /usr/local/bin/amm
```

Just starting to set up and trying to play around. Hoping to see the final book soon!

**Comment by lihaoyi** [comment]
Hi @yelinaung thanks for bringing this up! The Windows and Ubuntu instructions are still a bit rough, will update the current setup instructions with your suggestions

**Comment by Fealthas** [comment]
Do Ammonite and Mill both contain a copy of the scala compiler? This isn't really addressed anywhere. I think it would be helpful to spend like 3-4 sentences talking about how the scala_code -> bytecode -> jvm flow goes.

**Comment by iammortimer** [comment]
Just wanted to point out that the example link in 2.4.1 (installing Mill) goes to a 404: 
```
curl http://www.lihaoyi.com/mill/example-3.zip > example-3.zip
```

You might want to either put the file there or update the link mentioned. 

Otherwise i'm liking the first chapters very much. I'm coming from (recently) doing mostly Python programming and your approach makes it a lot easier to follow.

**Comment by lihaoyi** [comment]
@iammortimer should be fixed now, thanks for the report

**Comment by jayljohnson** [comment]
In section "2.5.2 Integrating IntelliJ with Mill" I set up my IntelliJ project SDK as the wsl location of the java installation. The following error happens after running the code or building from the IDE.  

```
Information:6/7/2020 11:30 PM - Build completed with 1 error and 0 warnings in 301 ms
Error:Cannot run program "\\wsl$\Ubuntu-18.04\usr\lib\jvm\java-11-openjdk-amd64\bin\java.exe" (in directory "C:\Users\username\AppData\Local\JetBrains\IdeaIC2020.1\compile-server"): CreateProcess error=2, The system cannot find the file specified
```

Should IntelliJ on Windows use the WSL installation of java?  Or should java also be installed directly in Windows, and IntelliJ should use that one?

Thank you!

_p.s. the first two chapters are going well for me, they are easy to read and insightful, and the examples are easy to follow._

**Comment by iammortimer** [comment]
You need to have java installed on Windows as well.

**Comment by lihaoyi** [comment]
Note that using the IntelliJ "run" button in the IDE will run your program on Windows, rather than within the WSL2/Ubuntu environment.

This might work, but I haven't tested the examples run in such a fashion myself. I ran through all the examples using IntelliJ for editing but running the code in WSL2/Ubuntu via the terminal

**Comment by pwissneth** [comment]
After importing the example-3 project into IntelliJ, the analysis of ExampleTests.scala returns an error saying "'Any' does not take parameters" starting with line 5. Is this an issue with the IntelliJ Scala plugin? Compiling and running the test via mill seems to be fine.

Do you have any ideas on this?

**Comment by kishvanchee** [comment]
Hi. Thank you for the book. I run Arch Linux as my system. I notice that when I had `java-11-openjdk` installed, I get an error when I run things inside `amm`. For example,

```
[kishore@archlinux ~]$ amm
Loading...
Welcome to the Ammonite Repl 2.1.4 (Scala 2.13.2 Java 11.0.7)
@ 1 
java.lang.UnsupportedClassVersionError: io/github/retronym/java9rtexport/Export has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0
  ammonite.runtime.Classpath$.classpath(Classpath.scala:77)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:85)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:57)
  ammonite.interp.Interpreter.$anonfun$processLine$4(Interpreter.scala:247)
  ammonite.util.Res$Success.flatMap(Res.scala:62)
  ammonite.interp.Interpreter.$anonfun$processLine$2(Interpreter.scala:240)
  ammonite.util.Catching.flatMap(Res.scala:115)
  ammonite.interp.Interpreter.processLine(Interpreter.scala:239)
  ammonite.repl.Repl.$anonfun$action$8(Repl.scala:197)
  ammonite.util.Res$Success.flatMap(Res.scala:62)
  ammonite.repl.Repl.$anonfun$action$4(Repl.scala:184)
  ammonite.repl.Scoped.$anonfun$flatMap$1(Signaller.scala:45)
  ammonite.repl.Signaller.apply(Signaller.scala:28)
  ammonite.repl.Scoped.flatMap(Signaller.scala:45)
  ammonite.repl.Scoped.flatMap$(Signaller.scala:45)
  ammonite.repl.Signaller.flatMap(Signaller.scala:16)
  ammonite.repl.Repl.$anonfun$action$2(Repl.scala:176)
  ammonite.util.Catching.flatMap(Res.scala:115)
  ammonite.repl.Repl.action(Repl.scala:168)
  ammonite.repl.Repl.loop$1(Repl.scala:208)
  ammonite.repl.Repl.run(Repl.scala:223)
  ammonite.Main.$anonfun$run$1(Main.scala:223)
  scala.Option.getOrElse(Option.scala:201)
  ammonite.Main.run(Main.scala:211)
  ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:413)
  ammonite.MainRunner.watchLoop(Main.scala:394)
  ammonite.MainRunner.runRepl(Main.scala:413)
  ammonite.Main$.main0(Main.scala:320)
  ammonite.Main$.main(Main.scala:270)
  ammonite.Main.main(Main.scala)
```

After I updated to `java-14-openjdk` things work fine for me now.

```
[kishore@archlinux ~]$ amm
Loading...
Welcome to the Ammonite Repl 2.1.4 (Scala 2.13.2 Java 14.0.1)
@ 1 + 1 
res0: Int = 2
```

Hoping this helps anyone else who comes across the same issue.

I have installed from the [community repo](https://www.archlinux.org/packages/community/any/ammonite/)

**Comment by ejayaraman** [comment]
Hi @lihaoyi. Thanks for publishing the book. When opening the example-3 project, IntelliJ, on Mac, is displaying an error `Method 'ivyDeps' needs override modifier` in build.sc  and also the error reported [here](https://github.com/handsonscala/handsonscala/issues/2#issuecomment-643125808) . 

I can run the example from command line. So it looks like a setup up issue with IntelliJ. If IntelliJ is being used here only for coding assistance, then that is fine. But just wanted to make sure I am not missing a setup. Thank you. 

**Update:** 
Even though IntelliJ highlights these errors, I could actually get the example running from the IDE run button.

**Comment by lihaoyi** [comment]
@ejayaraman that error is benign, and is a limitation with Intellij's understanding of the build.sc files. You can safely ignore it and move on, and perhaps in some future version of Intellij-Scala it will be resolved

**Comment by bikash119** [comment]
Can anyone please help me with VScode setup. I have installed metals 0.9.0. The scala metals is not firing up. For every command it says command '<command>' not found.

**Comment by ChemaGit** [comment]
Hi lihaoyi! First, congratulations for hands-on scala book, it is really a great book about Scala programming language and it is what I was looking for. Second, one question. Is there any way to install Ammonite in Windows 8.1? Maybe with cygwing? I don't know. Do you think is possible? Thanks in advance.

**Comment by ChemaGit** [comment]
Hi @lihaoyi sorry and forget my last comment because I finally found out: https://github.com/lihaoyi/Ammonite/issues/119

I could finally run ammonite via SBT on Windows 8.1, for each sbt project I have to paste the dependency in .build.sbt like you describe in https://ammonite.io/#Ammonite-REPL

Thanks.

**Comment by jim-miller** [comment]
Not sure if this has been caught yet, but the introductory paragraph to 2.5 IDE Support has a mistake in
"The most common editors used for working with Scala programs is IntelliJ or VSCode." 
I believe you meant "... are IntelliJ or VSCode.", not "... is IntelliJ or VSCode."

**Comment by Nayak11** [comment]
1)![image](https://user-images.githubusercontent.com/36310654/93717294-bfe66600-fb29-11ea-991b-c0acb4dbecf8.png)
Can someone help me debug this error.

2)How do i enter/paste multi-line in ammonite repl ? Shift enter is an option, but it's very tedious, is there any other better approach ?

**Comment by kluge** [comment]
After unpacking example-3.zip, compiling with `mill foo.compile` works fine. However when I try to run it:
```
$ mill foo.run
[28/36] foo.finalMainClass 
1 targets failed
foo.finalMainClass No main class specified or found
```

I found out that if I add the following inside object foo in build.sc, it works:

```
def mainClass = T{Some("foo.Example")}
```

Mill version is

```
Mill Build Tool version 0.8.0
Java version: 11.0.8, vendor: N/A, runtime: /usr/lib/jvm/java-11-openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "Linux", version: 5.8.13-arch1-1, arch: amd64
```

**Comment by isunix** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/7539407/96392356-6471cb80-11ee-11eb-9f37-a13106f39c5a.png">

Hi Haoyi, after running the command "./mill mill.scalalib.GenIdea/idea" for "example-3", and open the project in Intellij,it gives error message like 'Package names doesn't correspond to directories structure, this may cause problems with resolve to classes from this file '

**Comment by bklppr** [comment]
For VSCode on a Mac clicking "Import build" in Metals gave me `Cannot resolve external module mill.contrib.Bloop` until I changed the `.mill-version` from `0.8.0` as given in the online chapter to `0.9.3` as given in https://github.com/lihaoyi/mill.

**Comment by bac0nSandwich-zz** [comment]
in 2.5.2, i don't see the relevance of "**Note that every time you make changes to add
dependencies or add new modules to your build.sc, you need to re-run the ./mill
mill.scalalib.GenIdea/idea command, and restart IntelliJ to have it pick up the changes.**"

is this a note to remember to do for all my future projects? if yes, is that "mill.scalalib.GenIdea" URL always like that? how does it fit in my future projects?

**Comment by laiboonh** [comment]
> For VSCode on a Mac clicking "Import build" in Metals gave me `Cannot resolve external module mill.contrib.Bloop` until I changed the `.mill-version` from `0.8.0` as given in the online chapter to `0.9.3` as given in https://github.com/lihaoyi/mill.

Another way is to go to the directory and run `mill version`. This will cause the project to use whatever version specified in `mill` in this case `0.8.0` overriding what was installed in this case `0.9.3`

**Comment by cheapsolutionarchitect** [comment]
Regarding 2.5.3 Visual Studio Code Support,  it would be nice if there could be a reminder to check the current millw.bat used by metals in comparison to the current version found in https://github.com/lefou/millw. Metals uses an outdated one, so a hint to the configuration setting for mill within metals would be nice. The setting can be found via F1, Open Settings (UI), and update Extensions > Metals >Mill Script. I wasted some time, because the built-in script uses the bitadmin command which cannot be run without elevated rights, at least not on my Windows machine.

**Comment by jsatk** [comment]
I can't seem to run the `out.jar` generated by `./mill foo.assembly`.

OS: macOS 11.4 20F71 x86_64
Host: MacBookPro15,1
Kernel: 20.5.0
Shell: fish 3.2.2
Terminal: tmux
CPU: Intel i9-9980HK (16) @ 2.40GHz
GPU: Intel UHD Graphics 630, Radeon Pro 560X

```
$ scala --version
Scala code runner version 2.13.1 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.

$ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)

$ out/foo/assembly/dest/out.jar
Failed to execute process 'out/foo/assembly/dest/out.jar'. Reason:
exec: Exec format error
The file 'out/foo/assembly/dest/out.jar' is marked as an executable but could not be run by the operating system.
```

**Comment by zizu1985** [comment]
> Hi @lihaoyi. Thanks for publishing the book. When opening the example-3 project, IntelliJ, on Mac, is displaying an error `Method 'ivyDeps' needs override modifier` in build.sc and also the error reported [here](https://github.com/handsonscala/handsonscala/issues/2#issuecomment-643125808) .
> 
> I can run the example from command line. So it looks like a setup up issue with IntelliJ. If IntelliJ is being used here only for coding assistance, then that is fine. But just wanted to make sure I am not missing a setup. Thank you.
> 
> **Update:** Even though IntelliJ highlights these errors, I could actually get the example running from the IDE run button.

Is it possible to get some information how to configure Run Configuration in IntelliJ?
I'm not sure if mill - IntelliJ integration suppose to perform this configuration for us.
In my case I have nothing under Run button.
Everything is find when running in wsl2 terminal (directly or through terminal in IntelliJ).

My IntelliJ version is: IntelliJ IDEA 2021.2.2 (Community Edition)

**Comment by gawadrian** [comment]
`Exception in thread "main" java.lang.UnsatisfiedLinkError: (fat file, but missing compatible architecture (have (i386,x86_64), need (arm64e)))`

For people hitting the incompatibility issue above for M1 macs  when running `./mill foo.compile`, I simply installed https://com-lihaoyi.github.io/mill/mill/Intro_to_Mill.html and used that instead to run the mill commands (at least for Chapter 2)

```
brew install mill
mill foo.compile
mill foo.run
mill foo.test
```

It may just have different behavior such as the destination folder of the jar file: `out/foo/assembly.dest/out.jar` instead of `out/foo/assembly/dest/out.jar`

**Comment by livid16g** [comment]
Hello
I am @ section 2.4, Installing Mill

I have downloaded example-3.zip and unzipped it.

However, when i do "./mill foo.compile", the download does not complete and terminates with the following error:

(base) j00533938@lhrpbig100002:/sim_home/j00533938/github/example-3$ ./mill foo.compile
[1/25] mill.scalalib.ZincWorkerModule.compilerInterfaceClasspath | Downloading [2/2] artifacts (~0/0 bytes)
1 targets failed
mill.scalalib.ZincWorkerModule.compilerInterfaceClasspath
Resolution failed for 1 modules:
--------------------------------------------
  org.scala-sbt:compiler-interface:1.4.0-M1
        not found: /home/j00533938/.ivy2/local/org.scala-sbt/compiler-interface/1.4.0-M1/ivys/ivy.xml
        download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.4.0-M1/compiler-interface-1.4.0-M1.pom
        
        Any insight as how to resolve this please, much appreciated.
        
        Tks
        JO

**Comment by livid16g** [comment]
IntelliJ Plugin for Scala

**Comment by livid16g** [comment]
I have downloaded IntelliJ version 2022.3 on my Unix box and now trying to get the Scala plugin.

**Comment by livid16g** [comment]
There is no Scala installed plugin with IntelliJ and when i search in the "MarketPlace" it is not found.

**Comment by livid16g** [comment]
How do i get the scala plug-in For IntelliJ?

Tks

JO

**Comment by livid16g** [comment]
Was able to download from web and make it available in the plugins directory. Now Scala support is available.

**Comment by anh977** [comment]
I copied 2.18.scala, 2.19.scala, and 2.20.scala into a VSCode/mill setup.
I keep getting this error:
[error]  ... /WorkSpaces/ScalaWS/HOS/chap1/build.sc:14:23: not found: type Tests
[error]   object test extends Tests {
[error]                       ^
[error] one error found
1 targets failed
Does anyone know what's wrong.  I have no problems if I leave out the test stuff.

**Comment by foss-v** [comment]
> I copied 2.18.scala, 2.19.scala, and 2.20.scala into a VSCode/mill setup. I keep getting this error: [error] ... /WorkSpaces/ScalaWS/HOS/chap1/build.sc:14:23: not found: type Tests [error] object test extends Tests { [error] ^ [error] one error found 1 targets failed Does anyone know what's wrong. I have no problems if I leave out the test stuff.

@anh977 were you able to resolve this? I've just started the book and am hitting the same error.

**Comment by pmayd** [comment]
Here are my instructions for installing everything for Mac M2 chip in 2024:
1. Follow [this](https://medium.com/@manvendrapsingh/installing-many-jdk-versions-on-macos-dfc177bc8c2b) guide to install any Java version, basically using Homebrew and the `java_home` tool to switch versions, clean and easy
2. Install Ammonite: `brew install ammonite-repl`
3. For `mill`, follow the instructions [here](https://github.com/com-lihaoyi/mill). Again, just use `brew install mill` and mill is available. As each project can have its own version, it doesn't really matter which version we install globally.
4. To test the installation, download one of the examples from the `mill` [repo](https://github.com/com-lihaoyi/mill/tree/main/example/basic/1-simple-scala). If you don't want to work with git, you can directly download the examples as part of the [release](https://github.com/com-lihaoyi/mill/releases).

To actually run the code from the book, the given commands `./mill foo.compile` and `./mill foo.run` seem outdated but I could not find a good explanation as I am new to `mill`. A simple `./mill run` and `./mill test` works, though. So I guess you no longer need the package in front of it.

The only caveat with 2 is that it seems to come with Scala 3 and not 2, which is covered in the book. But you can just install an older version of `amm` with the instructions from the book or given [here](https://ammonite.io/#OlderScalaVersions)

**Comment by einnocent** [comment]
- To get rid of the "not found: type Tests" error, in the `build.sc` change:
```
  object test extends Tests{
    def testFrameworks = Seq("utest.runner.Framework")
```
to
```
  object test extends ScalaTests{
    def testFramework = "utest.runner.Framework"
```

- To get Mill working in your IntelliJ project, at the CLI do:
```
mill mill.idea.GenIdea/idea
```
- I got rid of "java.util.ServiceConfigurationError: xsbti.compile.CompilerInterface2: Provider xsbt.CompilerBridge not found" by changing `build.sc` `app.scalaVersion` from 2.13.2 to 2.13.14.

**Comment by abbadmus** [comment]
Thanks, it works why do we need to mill mill.idea.GenIdea/idea anytime we add to ivyDeps

**Comment by einnocent** [comment]
By default, IntelliJ doesn't refresh on changes to the build configuration. This is because the operation can be resource-intensive. 

You need to do this manually, either in the CLI by running the command you cited, or in the UI by opening the bsp tab and hitting the refresh (circular arrows) button. 

Alternatively, you can set IntelliJ to automatically refresh the project on build configuration changes. This is in the bsp tab under the wrench icon, which then reveals "Auto-reload settings".

**Comment by abbadmus** [comment]
this there a way mill will able to create your folder structure from your objects

object staticSite extends ScalaModule {

  def scalaVersion = "2.13.11"

  def ivyDeps: T[Agg[Dep]] = super.ivyDeps() ++ Agg(
    ivy"com.lihaoyi::scalatags:0.12.0",
    ivy"com.lihaoyi::mainargs:0.6.2",
    ivy"com.lihaoyi::scalatags:0.11.0",
    ivy"com.lihaoyi::os-lib::0.9.0",
    ivy"org.commonmark:commonmark:0.22.0"
  )

  object test extends ScalaTests {
    def ivyDeps: T[Agg[Dep]] = Agg(ivy"com.lihaoyi::utest:0.7.11")
    def testFramework = "utest.runner.Framework"
  }
}

eg staticSite/src, staticSite/test/src

**Comment by royce-chen** [comment]
pmayd's instructions (namely installing `mill` via Homebrew) got me close to a functioning example Mill project, was able to get the example project from the book working with a few more small tweaks:

### `build.sc` changes
Updated the `build.sc` file to use Scala `2.13.14`, changed `tests` to `ScalaTests`, and switched `TestFrameworks` to `TestFramework` (singular) and replaced the `Seq` wrapper around the framework
```scala
// build.sc
import mill._, scalalib._

object foo extends ScalaModule{
  def scalaVersion = "2.13.14"
  object test extends ScalaTests{
    def ivyDeps = Agg(ivy"com.lihaoyi::utest:0.7.4")
    def testFramework = "utest.runner.Framework"
  }
}

```

### Mill commands
`mill run` and `mill test` didn't work for me and resulted in these errors:
```
 $ mill run
[build.sc] [50/59] zincReportCachedProblems 
Cannot resolve run. Try `mill resolve _` or `mill resolve __.run` to see what's available.
```
```
$ mill test
[build.sc] [50/59] zincReportCachedProblems 
Cannot resolve test. Try `mill resolve _` or `mill resolve __.test` to see what's available.
```

But running `mill resolve __.run` and `mill resolve __.test` yielded  the commands that worked for me:
```
$ mill resolve __.run
[1/1] resolve 
foo.run
foo.test.run

$ mill resolve __.test
[1/1] resolve 
foo.test
foo.test.test
```

Thus, the following commands succeeded for me:
- **Test**`mill foo.test`: Runs and passes unit tests
- **Run**: `mill foo.run`: Prints `Hello World`

**Comment by matsilva** [comment]
I am on M3 and ran into issues trying to run the project as is.

Initially, I was getting this error.

```
./mill foo.compile
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /Users/akamat/Library/Caches/JNA/temp/jna13517458382605674103.tmp
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
```

Then after trying to clear some caches, I was getting this error.

```
Exception in thread "main" java.lang.Exception: Failed to connect to server
	at mill.main.client.MillClientMain.run(MillClientMain.java:200)
	at mill.main.client.MillClientMain.main0(MillClientMain.java:129)
	at mill.main.client.MillClientMain.main(MillClientMain.java:82)
```
I managed to get it to work finally by using either the `-i` or `--no-server` flags, but I could not tell you why it works 🤷 

* eg: `./mill --no-server foo.compile` or `./mill -i foo.compile` runs successfully.

**Comment by suchanun** [comment]
I am on Mac M4 and encountered the same issue as this:

> I am on M3 and ran into issues trying to run the project as is.
> 
> Initially, I was getting this error.
> 
> ```
> ./mill foo.compile
> Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /Users/akamat/Library/Caches/JNA/temp/jna13517458382605674103.tmp
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
> ```
> 
> Then after trying to clear some caches, I was getting this error.
> 
> ```
> Exception in thread "main" java.lang.Exception: Failed to connect to server
> 	at mill.main.client.MillClientMain.run(MillClientMain.java:200)
> 	at mill.main.client.MillClientMain.main0(MillClientMain.java:129)
> 	at mill.main.client.MillClientMain.main(MillClientMain.java:82)
> ```
> 
> I managed to get it to work finally by using either the `-i` or `--no-server` flags, but I could not tell you why it works 🤷
> 
> * eg: `./mill --no-server foo.compile` or `./mill -i foo.compile` runs successfully.

**Comment by decafbad** [comment]
2.1.6 mill projects link gives 404
